package(default_visibility = ["//visibility:public"])

load("//toolchains/cpp:generate.bzl",
     "generate_toolchain_suite",
     "generate_toolchains")

# non-platform
# with --cpu --crosstool_top
#generate_toolchain_suite()

# platform
generate_toolchains()

